### User register
POST http://localhost:8080/hibernate/register
Accept: application/json
Content-Type: application/json

{
  "username": "john",
  "password": "test123456!",
  "email": "john_lee@gmail.com",
  "age": 28,
  "agree": true
}